### ISSUE TITLE
Update documentation around rrule, rdate, exdate, and status

### ISSUE THREAD

**Issue by pinkerton** [pinkerton/django-ical#15]
The documentation around these features is hardly adequate or helpful to users. Update it 🥇

**Comment by hugotox** [comment]
At least an example would be very appreciated 🙏

**Comment by cleder** [comment]
I am writing some tests and documentation @ https://github.com/PrimarySite/django-ical/tree/feature/document-recurrence-CMS-2084/django_ical HTH

**Comment by pinkerton** [comment]
Resolved in #19 

Thank you @cleder!
