### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by drvid** [pinkerton/django-ical#22]
What is needed to make this code compatible with Python 3?

I haven't looked at the source too closely but `caniusepython3` reports no blocking dependencies.

**Comment by pinkerton** [comment]
Hi @drvid, the project has supported Python 3 for a while, although we could do a better job noting that in the README. PRs welcome, of course 😄

**Comment by webaholik** [comment]
Updated link for travis-ci: https://travis-ci.org/jazzband/django-ical
