### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by dgh--** [Pinkerton/django-ical#5]
Hi,

Just wondered whether django-ical is known to work with Django 1.8? Thanks!

**Comment by Pinkerton** [comment]
It should! I run it on 1.9.3, and it passes Django 1.8 tests with tox. I just recently took over maintenance of the project, so please let me know if you run into any issues!

**Comment by dgh--** [comment]
Great, thanks! Will let you know if I encounter any issues. :)

**Comment by gabn88** [comment]
Can confirm it works perfectly on 1.8 :+1:
